"""Build native 1-bit character tiles for the TinyBrain65 wordmark."""
from pathlib import Path
FONT={
'T':['11111','00100','00100','00100','00100','00100','00100'],
'I':['11111','00100','00100','00100','00100','00100','11111'],
'N':['10001','11001','11001','10101','10011','10011','10001'],
'Y':['10001','10001','01010','00100','00100','00100','00100'],
'B':['11110','10001','10001','11110','10001','10001','11110'],
'R':['11110','10001','10001','11110','10100','10010','10001'],
'A':['01110','10001','10001','11111','10001','10001','10001'],
'6':['01111','10000','10000','11110','10001','10001','01110'],
'5':['11111','10000','10000','11110','00001','00001','11110'],
}
def main():
    word='TINYBRAIN65';width=(len(word)*36-6+7)//8*8;height=32
    pixels=[[0]*width for _ in range(height)]
    for i,c in enumerate(word):
        for y,row in enumerate(FONT[c]):
            for x,v in enumerate(row):
                if v=='1':
                    for yy in range(y*4,y*4+4):
                        for xx in range(i*36+x*6,i*36+x*6+6):pixels[yy][xx]=1
    glyphs=[];cells=[]
    for y in range(0,height,8):
        for x in range(0,width,8):
            glyph=bytes(sum(pixels[y+j][x+k]<<(7-k) for k in range(8)) for j in range(8))
            if not any(glyph):cells.append(32);continue
            if glyph not in glyphs:glyphs.append(glyph)
            cells.append(128+glyphs.index(glyph))
    assert len(glyphs)<=128
    def arr(name,values):return 'static const uint8_t '+name+'[]={'+','.join(map(str,values))+'};\n'
    text='/* Generated by make_title.py; native monochrome tiles, no CRT effects. */\n'
    text+=f'#define TITLE_COLS {width//8}\n#define TITLE_ROWS 4\n'
    text+=arr('title_glyphs',b''.join(glyphs))+arr('title_cells',cells)
    (Path(__file__).parent/'native/title.h').write_text(text)
    print('Title:',width,'x',height,'pixels;',len(glyphs),'unique tiles')
if __name__=='__main__':main()
